/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { SUGARToken, SUGARTokenInterface } from "../SUGARToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class SUGARToken__factory {
  static readonly abi = _abi;
  static createInterface(): SUGARTokenInterface {
    return new utils.Interface(_abi) as SUGARTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SUGARToken {
    return new Contract(address, _abi, signerOrProvider) as SUGARToken;
  }
}
